//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BananaSplit.Data
{
    public partial class ApiAccess
    {
        #region Primitive Properties
    
        public virtual int ApiAccessId
        {
            get;
            set;
        }
    
        public virtual string CompanyName
        {
            get;
            set;
        }
    
        public virtual string AppKey
        {
            get;
            set;
        }
    
        public virtual long MemberId
        {
            get { return _memberId; }
            set
            {
                if (_memberId != value)
                {
                    if (Member != null && Member.MemberId != value)
                    {
                        Member = null;
                    }
                    _memberId = value;
                }
            }
        }
        private long _memberId;
    
        public virtual string SecretKey
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateUpdated
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Member Member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    FixupMember(previousValue);
                }
            }
        }
        private Member _member;

        #endregion

        #region Association Fixup
    
        private void FixupMember(Member previousValue)
        {
            if (previousValue != null && previousValue.ApiAccesses.Contains(this))
            {
                previousValue.ApiAccesses.Remove(this);
            }
    
            if (Member != null)
            {
                if (!Member.ApiAccesses.Contains(this))
                {
                    Member.ApiAccesses.Add(this);
                }
                if (MemberId != Member.MemberId)
                {
                    MemberId = Member.MemberId;
                }
            }
        }

        #endregion

    }
}
