//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BananaSplit.Data
{
    public partial class Invoice
    {
        #region Primitive Properties
    
        public virtual long InvoiceId
        {
            get;
            set;
        }
    
        public virtual long ManagingMemberId
        {
            get { return _managingMemberId; }
            set
            {
                if (_managingMemberId != value)
                {
                    if (Member != null && Member.MemberId != value)
                    {
                        Member = null;
                    }
                    _managingMemberId = value;
                }
            }
        }
        private long _managingMemberId;
    
        public virtual long MemberId
        {
            get { return _memberId; }
            set
            {
                if (_memberId != value)
                {
                    if (Member1 != null && Member1.MemberId != value)
                    {
                        Member1 = null;
                    }
                    _memberId = value;
                }
            }
        }
        private long _memberId;
    
        public virtual decimal Amount
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DateSent
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateUpdated
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Member Member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    FixupMember(previousValue);
                }
            }
        }
        private Member _member;
    
        public virtual Member Member1
        {
            get { return _member1; }
            set
            {
                if (!ReferenceEquals(_member1, value))
                {
                    var previousValue = _member1;
                    _member1 = value;
                    FixupMember1(previousValue);
                }
            }
        }
        private Member _member1;

        #endregion
        #region Association Fixup
    
        private void FixupMember(Member previousValue)
        {
            if (previousValue != null && previousValue.Invoices.Contains(this))
            {
                previousValue.Invoices.Remove(this);
            }
    
            if (Member != null)
            {
                if (!Member.Invoices.Contains(this))
                {
                    Member.Invoices.Add(this);
                }
                if (ManagingMemberId != Member.MemberId)
                {
                    ManagingMemberId = Member.MemberId;
                }
            }
        }
    
        private void FixupMember1(Member previousValue)
        {
            if (previousValue != null && previousValue.Invoices1.Contains(this))
            {
                previousValue.Invoices1.Remove(this);
            }
    
            if (Member1 != null)
            {
                if (!Member1.Invoices1.Contains(this))
                {
                    Member1.Invoices1.Add(this);
                }
                if (MemberId != Member1.MemberId)
                {
                    MemberId = Member1.MemberId;
                }
            }
        }

        #endregion
    }
}
