//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BananaSplit.Data
{
    public partial class MemberPartnership
    {
        #region Primitive Properties
    
        public virtual long MemberPartnershipId
        {
            get;
            set;
        }
    
        public virtual long PartnershipId
        {
            get { return _partnershipId; }
            set
            {
                if (_partnershipId != value)
                {
                    if (Partnership != null && Partnership.PartnershipId != value)
                    {
                        Partnership = null;
                    }
                    _partnershipId = value;
                }
            }
        }
        private long _partnershipId;
    
        public virtual long MemberId
        {
            get { return _memberId; }
            set
            {
                if (_memberId != value)
                {
                    if (Member != null && Member.MemberId != value)
                    {
                        Member = null;
                    }
                    _memberId = value;
                }
            }
        }
        private long _memberId;
    
        public virtual bool IsManagingMember
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateUpdated
        {
            get;
            set;
        }
    
        public virtual long HasESigned
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DateESigned
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Member Member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    FixupMember(previousValue);
                }
            }
        }
        private Member _member;
    
        public virtual Partnership Partnership
        {
            get { return _partnership; }
            set
            {
                if (!ReferenceEquals(_partnership, value))
                {
                    var previousValue = _partnership;
                    _partnership = value;
                    FixupPartnership(previousValue);
                }
            }
        }
        private Partnership _partnership;

        #endregion

        #region Association Fixup
    
        private void FixupMember(Member previousValue)
        {
            if (previousValue != null && previousValue.MemberPartnerships.Contains(this))
            {
                previousValue.MemberPartnerships.Remove(this);
            }
    
            if (Member != null)
            {
                if (!Member.MemberPartnerships.Contains(this))
                {
                    Member.MemberPartnerships.Add(this);
                }
                if (MemberId != Member.MemberId)
                {
                    MemberId = Member.MemberId;
                }
            }
        }
    
        private void FixupPartnership(Partnership previousValue)
        {
            if (previousValue != null && previousValue.MemberPartnerships.Contains(this))
            {
                previousValue.MemberPartnerships.Remove(this);
            }
    
            if (Partnership != null)
            {
                if (!Partnership.MemberPartnerships.Contains(this))
                {
                    Partnership.MemberPartnerships.Add(this);
                }
                if (PartnershipId != Partnership.PartnershipId)
                {
                    PartnershipId = Partnership.PartnershipId;
                }
            }
        }

        #endregion

    }
}
