//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BananaSplit.Data
{
    public partial class PartnerTicket
    {
        #region Primitive Properties
    
        public virtual long PartnerTicketId
        {
            get;
            set;
        }
    
        public virtual long TicketPriceId
        {
            get { return _ticketPriceId; }
            set
            {
                if (_ticketPriceId != value)
                {
                    if (TicketPrice != null && TicketPrice.TicketPriceId != value)
                    {
                        TicketPrice = null;
                    }
                    _ticketPriceId = value;
                }
            }
        }
        private long _ticketPriceId;
    
        public virtual long MemberId
        {
            get { return _memberId; }
            set
            {
                if (_memberId != value)
                {
                    if (Member != null && Member.MemberId != value)
                    {
                        Member = null;
                    }
                    _memberId = value;
                }
            }
        }
        private long _memberId;
    
        public virtual Nullable<long> DateESigned
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateUpdated
        {
            get;
            set;
        }
    
        public virtual long PartnerShipId
        {
            get { return _partnerShipId; }
            set
            {
                if (_partnerShipId != value)
                {
                    if (Partnership != null && Partnership.PartnershipId != value)
                    {
                        Partnership = null;
                    }
                    _partnerShipId = value;
                }
            }
        }
        private long _partnerShipId;

        #endregion
        #region Navigation Properties
    
        public virtual Member Member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    FixupMember(previousValue);
                }
            }
        }
        private Member _member;
    
        public virtual Partnership Partnership
        {
            get { return _partnership; }
            set
            {
                if (!ReferenceEquals(_partnership, value))
                {
                    var previousValue = _partnership;
                    _partnership = value;
                    FixupPartnership(previousValue);
                }
            }
        }
        private Partnership _partnership;
    
        public virtual TicketPrice TicketPrice
        {
            get { return _ticketPrice; }
            set
            {
                if (!ReferenceEquals(_ticketPrice, value))
                {
                    var previousValue = _ticketPrice;
                    _ticketPrice = value;
                    FixupTicketPrice(previousValue);
                }
            }
        }
        private TicketPrice _ticketPrice;

        #endregion
        #region Association Fixup
    
        private void FixupMember(Member previousValue)
        {
            if (previousValue != null && previousValue.PartnerTickets.Contains(this))
            {
                previousValue.PartnerTickets.Remove(this);
            }
    
            if (Member != null)
            {
                if (!Member.PartnerTickets.Contains(this))
                {
                    Member.PartnerTickets.Add(this);
                }
                if (MemberId != Member.MemberId)
                {
                    MemberId = Member.MemberId;
                }
            }
        }
    
        private void FixupPartnership(Partnership previousValue)
        {
            if (previousValue != null && previousValue.PartnerTickets.Contains(this))
            {
                previousValue.PartnerTickets.Remove(this);
            }
    
            if (Partnership != null)
            {
                if (!Partnership.PartnerTickets.Contains(this))
                {
                    Partnership.PartnerTickets.Add(this);
                }
                if (PartnerShipId != Partnership.PartnershipId)
                {
                    PartnerShipId = Partnership.PartnershipId;
                }
            }
        }
    
        private void FixupTicketPrice(TicketPrice previousValue)
        {
            if (previousValue != null && previousValue.PartnerTickets.Contains(this))
            {
                previousValue.PartnerTickets.Remove(this);
            }
    
            if (TicketPrice != null)
            {
                if (!TicketPrice.PartnerTickets.Contains(this))
                {
                    TicketPrice.PartnerTickets.Add(this);
                }
                if (TicketPriceId != TicketPrice.TicketPriceId)
                {
                    TicketPriceId = TicketPrice.TicketPriceId;
                }
            }
        }

        #endregion
    }
}
