//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BananaSplit.Data
{
    public partial class Partnership
    {
        #region Primitive Properties
    
        public virtual long PartnershipId
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateUpdated
        {
            get;
            set;
        }
    
        public virtual short MaxNumberOfTickets
        {
            get;
            set;
        }
    
        public virtual long ManagingMemberId
        {
            get { return _managingMemberId; }
            set
            {
                if (_managingMemberId != value)
                {
                    if (Member != null && Member.MemberId != value)
                    {
                        Member = null;
                    }
                    _managingMemberId = value;
                }
            }
        }
        private long _managingMemberId;

        #endregion
        #region Navigation Properties
    
        public virtual Member Member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    FixupMember(previousValue);
                }
            }
        }
        private Member _member;
    
        public virtual ICollection<PartnerTicket> PartnerTickets
        {
            get
            {
                if (_partnerTickets == null)
                {
                    var newCollection = new FixupCollection<PartnerTicket>();
                    newCollection.CollectionChanged += FixupPartnerTickets;
                    _partnerTickets = newCollection;
                }
                return _partnerTickets;
            }
            set
            {
                if (!ReferenceEquals(_partnerTickets, value))
                {
                    var previousValue = _partnerTickets as FixupCollection<PartnerTicket>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPartnerTickets;
                    }
                    _partnerTickets = value;
                    var newValue = value as FixupCollection<PartnerTicket>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPartnerTickets;
                    }
                }
            }
        }
        private ICollection<PartnerTicket> _partnerTickets;

        #endregion
        #region Association Fixup
    
        private void FixupMember(Member previousValue)
        {
            if (previousValue != null && previousValue.Partnerships.Contains(this))
            {
                previousValue.Partnerships.Remove(this);
            }
    
            if (Member != null)
            {
                if (!Member.Partnerships.Contains(this))
                {
                    Member.Partnerships.Add(this);
                }
                if (ManagingMemberId != Member.MemberId)
                {
                    ManagingMemberId = Member.MemberId;
                }
            }
        }
    
        private void FixupPartnerTickets(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PartnerTicket item in e.NewItems)
                {
                    item.Partnership = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PartnerTicket item in e.OldItems)
                {
                    if (ReferenceEquals(item.Partnership, this))
                    {
                        item.Partnership = null;
                    }
                }
            }
        }

        #endregion
    }
}
