//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BananaSplit.Data
{
    public partial class SeasonYear
    {
        #region Primitive Properties
    
        public virtual int SeasonYearsId
        {
            get;
            set;
        }
    
        public virtual string Years
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Season> Seasons
        {
            get
            {
                if (_seasons == null)
                {
                    var newCollection = new FixupCollection<Season>();
                    newCollection.CollectionChanged += FixupSeasons;
                    _seasons = newCollection;
                }
                return _seasons;
            }
            set
            {
                if (!ReferenceEquals(_seasons, value))
                {
                    var previousValue = _seasons as FixupCollection<Season>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSeasons;
                    }
                    _seasons = value;
                    var newValue = value as FixupCollection<Season>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSeasons;
                    }
                }
            }
        }
        private ICollection<Season> _seasons;

        #endregion

        #region Association Fixup
    
        private void FixupSeasons(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Season item in e.NewItems)
                {
                    item.SeasonYear = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Season item in e.OldItems)
                {
                    if (ReferenceEquals(item.SeasonYear, this))
                    {
                        item.SeasonYear = null;
                    }
                }
            }
        }

        #endregion

    }
}
