//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BananaSplit.Data
{
    public partial class Team
    {
        #region Primitive Properties
    
        public virtual long TeamId
        {
            get;
            set;
        }
    
        public virtual string TeamName
        {
            get;
            set;
        }
    
        public virtual int LocationId
        {
            get { return _locationId; }
            set
            {
                if (_locationId != value)
                {
                    if (Location != null && Location.LocationId != value)
                    {
                        Location = null;
                    }
                    _locationId = value;
                }
            }
        }
        private int _locationId;
    
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateUpdated
        {
            get;
            set;
        }
    
        public virtual int TeamTypeId
        {
            get { return _teamTypeId; }
            set
            {
                if (_teamTypeId != value)
                {
                    if (TeamType != null && TeamType.TeamTypeId != value)
                    {
                        TeamType = null;
                    }
                    _teamTypeId = value;
                }
            }
        }
        private int _teamTypeId;
    
        public virtual bool IsActive
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Location Location
        {
            get { return _location; }
            set
            {
                if (!ReferenceEquals(_location, value))
                {
                    var previousValue = _location;
                    _location = value;
                    FixupLocation(previousValue);
                }
            }
        }
        private Location _location;
    
        public virtual ICollection<TicketPrice> TicketPrices
        {
            get
            {
                if (_ticketPrices == null)
                {
                    var newCollection = new FixupCollection<TicketPrice>();
                    newCollection.CollectionChanged += FixupTicketPrices;
                    _ticketPrices = newCollection;
                }
                return _ticketPrices;
            }
            set
            {
                if (!ReferenceEquals(_ticketPrices, value))
                {
                    var previousValue = _ticketPrices as FixupCollection<TicketPrice>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTicketPrices;
                    }
                    _ticketPrices = value;
                    var newValue = value as FixupCollection<TicketPrice>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTicketPrices;
                    }
                }
            }
        }
        private ICollection<TicketPrice> _ticketPrices;
    
        public virtual ICollection<Season> Seasons
        {
            get
            {
                if (_seasons == null)
                {
                    var newCollection = new FixupCollection<Season>();
                    newCollection.CollectionChanged += FixupSeasons;
                    _seasons = newCollection;
                }
                return _seasons;
            }
            set
            {
                if (!ReferenceEquals(_seasons, value))
                {
                    var previousValue = _seasons as FixupCollection<Season>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSeasons;
                    }
                    _seasons = value;
                    var newValue = value as FixupCollection<Season>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSeasons;
                    }
                }
            }
        }
        private ICollection<Season> _seasons;
    
        public virtual TeamType TeamType
        {
            get { return _teamType; }
            set
            {
                if (!ReferenceEquals(_teamType, value))
                {
                    var previousValue = _teamType;
                    _teamType = value;
                    FixupTeamType(previousValue);
                }
            }
        }
        private TeamType _teamType;

        #endregion
        #region Association Fixup
    
        private void FixupLocation(Location previousValue)
        {
            if (previousValue != null && previousValue.Teams.Contains(this))
            {
                previousValue.Teams.Remove(this);
            }
    
            if (Location != null)
            {
                if (!Location.Teams.Contains(this))
                {
                    Location.Teams.Add(this);
                }
                if (LocationId != Location.LocationId)
                {
                    LocationId = Location.LocationId;
                }
            }
        }
    
        private void FixupTeamType(TeamType previousValue)
        {
            if (previousValue != null && previousValue.Teams.Contains(this))
            {
                previousValue.Teams.Remove(this);
            }
    
            if (TeamType != null)
            {
                if (!TeamType.Teams.Contains(this))
                {
                    TeamType.Teams.Add(this);
                }
                if (TeamTypeId != TeamType.TeamTypeId)
                {
                    TeamTypeId = TeamType.TeamTypeId;
                }
            }
        }
    
        private void FixupTicketPrices(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (TicketPrice item in e.NewItems)
                {
                    item.Team = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TicketPrice item in e.OldItems)
                {
                    if (ReferenceEquals(item.Team, this))
                    {
                        item.Team = null;
                    }
                }
            }
        }
    
        private void FixupSeasons(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Season item in e.NewItems)
                {
                    item.Team = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Season item in e.OldItems)
                {
                    if (ReferenceEquals(item.Team, this))
                    {
                        item.Team = null;
                    }
                }
            }
        }

        #endregion
    }
}
